# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98579ef4b2a31a3c062b5b5cfda6f0b2350501309b7b75abe836450a4f2dd092f7e1e5bdd04bc9eb9ff50abca2d73ebe53fe55e9ff2a5953ee4af435e73da92f

test:
  secret_key_base: 8aca0749bbfcc6feb9e167c41b2e0bc051380ad2ea40fc71eec453446659c3b5be5efb93e1b33e5df9c70c2062253db53676c49a8cb333457e60dc29bd6aee14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
